### ISSUE TITLE
Possible error in DataSimulationFunction.m

### ISSUE THREAD

**Issue by evaalonsoortiz** [neuropoly/Susceptibility-Separation-Phantom#1]
To simulate the field offset due to a given susceptibility distribution, one approach is to perform a convolution between the dipole kernel and the susceptibility distribution in Fourier space (as described by Marques and Bowtell in https://onlinelibrary.wiley.com/doi/10.1002/cmr.b.20034). This has previously been implemented and well documented in the following repo: https://github.com/evaalonsoortiz/Fourier-based-field-estimation

In that repo, the convolution is performed in FBFest.m:

First the null frequency of the dipole kernel in Fourier space is centered 
` kernel = fftshift(1/3 - kz.^2./k2); % multiplication with b0 only in test script for field in Hz`

Next, the value at k = 0 is set to 1/3
`kernel(1, 1, 1) = 1/3; % multiplication with b0 only in test script for field in Hz`

After that, we compute the FT of the susceptibility distribution and add a buffer to avoid circular convolution:
```
FT_chi = fftn(obj.sus, obj.dim_with_buffer);
FT_chi(1, 1, 1) = FT_chi(1,1,1) + prod(obj.dim_with_buffer) * susout;
```

Finally, we multiply the dipole kernel with the FT of the susceptibility distribution, and take the inverse FT of that:
```
bdzFFT = kernel .* FT_chi;
obj.volume = real(ifftn(bdzFFT));
```

If I compare with what you did, it looks like you first take a definition of a dipole kernel:
https://github.com/neuropoly/Susceptibility-Separation-Phantom/blob/6733f8c790cfba44fb7e3e2f2e2aa6e199ba371a/func/DataSimulationFunction.m#L35

it doesn't state anywhere where this definition comes from, and what it is (if it comes from the QSM challenge code, then you should at least write out the definition in a comment here so that we can follow all of the steps).
I'm going to assume it's the definition of the dipole kernel in Fourier space, so this: (1/3 - kz.^2./k2), hopefully with the null frequency centered. 

Next, you do this:
https://github.com/neuropoly/Susceptibility-Separation-Phantom/blob/6733f8c790cfba44fb7e3e2f2e2aa6e199ba371a/func/DataSimulationFunction.m#L39

This looks like you are multiplying the dipole kernel (presumably the Fourier space version) with the susceptibility distribution (in the spatial domain, not the Fourier domain - which is problematic). Then, you take the Fourier transform of that? And finally, the inverse Fourier transform. Taking the inverse FT of the FT should be like doing nothing, so in brief, your "field" is = chi_map * D (susceptibility distribution, multiplied by the dipole kernel in Fourier space).

If I am interpreting things incorrectly, let me know, because such as it appears, this is riddled with errors.

In any case, we should absolutely not be re-writing code several times across projects that do the same thing. I have confidence in the FBFest.m code. @CharlesPageot is rewriting that code in python and incorporating it into the shimming-toolbox (see https://github.com/shimming-toolbox/susceptibility-to-fieldmap-fft). We should only use **one** set of code when simulating a field distribution due to a susceptibility distribution not multiple different implementations. The same goes for @sriosq 's code which also does the same thing. 

Conclusion:
1. We should all move to using @CharlesPageot 's new code in the shimming toolbox for simulating B0 maps.
2. We should all move to using the Shimming toolbox's MR simulation code (https://github.com/shimming-toolbox/shimming-toolbox/blob/master/shimmingtoolbox/simulate/numerical_model.py) for all GRE simulations. @Danirid for your MR simulations, I know that they are a bit more sophisticated that what's done in numerical_model.py. Perhaps numerical_model.py could be updated to provide more options. We can discuss a way forward there, but my goal is for everyone to use the same codebase for everything.

**Comment by Danirid** [comment]
'''

**Comment by Danirid** [comment]
```matlab
D = create_dipole_kernel(B0_dir, voxel_size, 2 * dims, 1);
```
In this line the dipole is created using the function *create_dipole_kernel.m* which is QSM challenge function. I will ad few comments explaining that.

As for :
```matlab
field= real(ifftn(fftn(chitemp).*(D)))  ; 
```
D is in the Fourier domain, chitemp is transferred to the Fourier domain using *fftn* before multiplying it with D. The results of this multiplication is then inversed using *ifftn*.

This is the field that I got using my code:

![image](https://github.com/neuropoly/Susceptibility-Separation-Phantom/assets/77506715/1c4cee8f-6594-45d9-aabb-f72c57b56e38)

Is @CharlesPageot code in python? If yes then if I want to use it, I should maybe consider switch my entire code to python?

**Comment by evaalonsoortiz** [comment]
Ah, I missed the closing bracket after `chitemp` here:
`field= real(ifftn(fftn(chitemp).*(D)))  ; `

I downloaded `create_dipole_kernel.m` and can confirm that the dipole kernel is computed in k-space, assuming the "1" in:
`D = create_dipole_kernel(B0_dir, voxel_size, 2 * dims, 1);`
sets the flag to compute it in k-space. And, the central frequency is shifted.

I'm much more confident that your code is doing what we want now. 

That being said, I still think it's unwise to have several versions of code that is doing the same thing. Yes, @CharlesPageot 's code is in python. But the matlab version also exists: https://github.com/evaalonsoortiz/Fourier-based-field-estimation
The same is true for the GRE simulation code, there are both python and matlab versions.

Generally, the lab is moving towards doing everything in python. In your case though, your project uses matlab code from the QSM challenge 2.0 repo. In order to decide if you should convert everything to python, it would be good to go over everything that you use from the 2.0 repo is a systematic way. We can try and do that in an organized way in another issue. Could you open one and get the conversation started?

**Comment by evaalonsoortiz** [comment]
I'm closing this issue and will reopen another one to document the conversation about using one code version across projects for B0 and MR simulations.
